version: '3.4'

services:
  generic:
    image: ${DOCKER_REGISTRY-}generic
    build:
      context: .
      dockerfile: 01Generic/Dockerfile

  reflection:
    image: ${DOCKER_REGISTRY-}reflection
    build:
      context: .
      dockerfile: 02Reflection/Reflection/Dockerfile

